# Generated by Django 3.2.7 on 2021-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableGeded',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Loan Providers'), (1, 'Loan Customers'), (2, 'Bank Personnel')], default=1),
        ),
    ]
