# Generated by Django 3.2.7 on 2021-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210913_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Loan Providers'), (2, 'Loan Customers'), (3, 'Bank Personnel')], default=2),
        ),
    ]
