# Generated by Django 3.2.3 on 2021-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20210915_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='bankAccountMoney',
            field=models.FloatField(default=0.7),
        ),
    ]
