# Generated by Django 3.2.3 on 2021-09-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_attribute_bankaccountmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loansfunds',
            name='Type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='BankProfitRate',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='attribute',
            name='RiskRate',
            field=models.FloatField(default=0.02),
        ),
        migrations.AddField(
            model_name='attribute',
            name='maxAcceptedLoan',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='attribute',
            name='maxAcceptedLoanFund',
            field=models.IntegerField(default=500000),
        ),
        migrations.AddField(
            model_name='loan',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='max',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanterm',
            name='min',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='bankAccountMoney',
            field=models.FloatField(default=100000),
        ),
    ]
