# Generated by Django 3.2.3 on 2021-09-16 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0006_auto_20210915_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansfunds',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Main.loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bankPersonnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loansApproved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanTerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='Main.loanterm'),
        ),
        migrations.AlterField(
            model_name='loanfundterm',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Loan Providers'), (2, 'Loan Customers'), (3, 'Bank Personnel')], default=2),
        ),
        migrations.AlterField(
            model_name='loanfundterm',
            name='bankPersonnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoanFundTerm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loansfunds',
            name='loanFundTerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loanFunds', to='Main.loanfundterm'),
        ),
        migrations.AlterField(
            model_name='loansfunds',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Loan Providers'), (2, 'Loan Customers'), (3, 'Bank Personnel')], default=2),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='bankPersonnal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoanTerm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
