# Generated by Django 3.2.3 on 2021-09-16 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0007_auto_20210916_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansfunds',
            name='bankPersonnal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='loanFunds', to='auth.user'),
            preserve_default=False,
        ),
    ]
