# Generated by Django 3.2.3 on 2021-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20210916_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfundterm',
            name='duration',
            field=models.IntegerField(default=12),
        ),
    ]
