# Generated by Django 3.2.7 on 2021-09-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20210923_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanterm',
            name='isActive',
        ),
    ]
